### ISSUE TITLE
Selection boxes disabled after render

### ISSUE THREAD

**Issue by JonathanTroyer** [JonathanTroyer/Progress-Renderer#1]
From Patigooo on Steam:
> ...after it renders, it won't let any selection box popup on the things I click on. It only pops up for the colony bar. Every time this happens I have to go to the main menu...

**Comment by DeJota2212** [comment]
Happens if pixel per cell is set to more than 59:
![image](https://user-images.githubusercontent.com/42788719/77479423-847b1100-6dfe-11ea-9dea-1bf13ee5e85c.png)

Happens 100% of the time in my save that had Prepare Carefully installed and ppc set to >59, however, i was unable to replicate it in a brand new save.

It's not only the selection boxes that disappear, it's anything selected here
![image](https://user-images.githubusercontent.com/42788719/77478322-8c39b600-6dfc-11ea-94cc-e1df60780746.png)

No render is produced.
Nothing related appears on debug.

Example of the issue:
Before rendering:
![Image 1](https://user-images.githubusercontent.com/42788719/77478228-690f0680-6dfc-11ea-9d91-8518853cb746.jpg)

After rendering:
![Image 2](https://user-images.githubusercontent.com/42788719/77478224-66141600-6dfc-11ea-9608-8a0453ea27f4.jpg)

I suspect the error has something to do with the mod disabling some visuals to render and not enabling them afterwards.

**Comment by JonathanTroyer** [comment]
This is a really good issue report! Unfortunately, I'm unable to reproduce this issue both in an old save and a new save. The only thing I think could be happening is that somehow the rendering crashes in the middle and then never gets back to setting the map back to normal. I've added a try/catch to hopefully mitigate this, so let me know if you run across it again!
